on:
  push:
    branches: [main]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: flutter build ...
      - uses: actions/upload-artifact@v3
        with:
          name: release-build
          path: build/

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-build
      - uses: softprops/action-gh-release@v1
        with:
          files: build/**